"""Initial schema: properties, units, applications, decisions, viewings, offers

Revision ID: 0001
Revises:
Create Date: 2026-09-02

Hand-written rather than autogenerated so the constraints SPEC section 4 asks
for are visible in the migration and not just implied by the models.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

HOUSING_FORMS = ("vapaarahoitteinen", "lyhyt_korkotuki", "tarveharkintainen", "asumisoikeus")
LISTING_TYPES = ("vuokra", "myynti")
AVAILABILITIES = ("vapaa", "vapautuu", "sopimuksella")
APPLICATION_STATUSES = ("luonnos", "lahetetty", "vanhentunut")
MEMBER_ROLES = ("paahakija", "toinen", "muu")
NEED_SITUATIONS = ("asunnoton", "irtisanottu", "ahtaasti", "ei_tarvetta")
OUTCOMES = ("kelpoinen", "puuttuvat_tiedot", "ei_kelpoinen")


def _enum(*values: str, name: str) -> sa.Enum:
    return sa.Enum(*values, name=name, native_enum=False, create_constraint=True)


# A booking must not be insertable once capacity is reached. The row lock on the
# viewing serialises concurrent inserts for the same viewing, so two sessions
# racing on the last seat cannot both read the same count.
CAPACITY_GUARD_FUNCTION = """
CREATE OR REPLACE FUNCTION viewing_booking_capacity_guard() RETURNS trigger AS $fn$
DECLARE
    cap integer;
    taken integer;
BEGIN
    SELECT capacity INTO cap FROM viewings WHERE id = NEW.viewing_id FOR UPDATE;
    IF cap IS NULL THEN
        RAISE EXCEPTION 'VIEWING_NOT_FOUND' USING ERRCODE = 'P0002';
    END IF;
    SELECT count(*) INTO taken FROM viewing_bookings WHERE viewing_id = NEW.viewing_id;
    IF taken >= cap THEN
        RAISE EXCEPTION 'VIEWING_FULL' USING ERRCODE = 'P0001';
    END IF;
    RETURN NEW;
END;
$fn$ LANGUAGE plpgsql;
"""

CAPACITY_GUARD_TRIGGER = """
CREATE TRIGGER trg_viewing_booking_capacity
BEFORE INSERT ON viewing_bookings
FOR EACH ROW EXECUTE FUNCTION viewing_booking_capacity_guard();
"""


def upgrade() -> None:
    op.create_table(
        "properties",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("street", sa.String(length=160), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("housing_form", _enum(*HOUSING_FORMS, name="housing_form"), nullable=False),
        sa.Column("built_year", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "units",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("property_id", sa.BigInteger(), nullable=False),
        sa.Column("unit_number", sa.String(length=20), nullable=False),
        sa.Column("rooms", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("area_m2", sa.Numeric(precision=6, scale=1), nullable=False),
        sa.Column("listing_type", _enum(*LISTING_TYPES, name="listing_type"), nullable=False),
        sa.Column("rent_eur", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("price_eur", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("deposit_eur", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("availability", _enum(*AVAILABILITIES, name="availability"), nullable=False),
        sa.Column("available_from", sa.Date(), nullable=True),
        sa.Column("description_fi", sa.Text(), nullable=False),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "(listing_type = 'vuokra' AND rent_eur IS NOT NULL AND price_eur IS NULL)"
            " OR (listing_type = 'myynti' AND price_eur IS NOT NULL AND rent_eur IS NULL)",
            name="ck_units_listing_price",
        ),
        sa.CheckConstraint("area_m2 > 0", name="ck_units_area_positive"),
        sa.CheckConstraint("rooms > 0", name="ck_units_rooms_positive"),
    )
    op.create_index("ix_units_property_id", "units", ["property_id"])

    op.create_table(
        "applications",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("edit_token", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status", _enum(*APPLICATION_STATUSES, name="application_status"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contact_name", sa.String(length=160), nullable=True),
        sa.Column("contact_email", sa.String(length=254), nullable=True),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("order_number", sa.String(length=20), nullable=True),
        sa.Column("deposit_acknowledged", sa.Boolean(), nullable=True),
        sa.Column("credit_default_flag", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edit_token", name="uq_applications_edit_token"),
    )

    op.create_table(
        "household_members",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("role", _enum(*MEMBER_ROLES, name="member_role"), nullable=False),
        sa.Column("birth_year", sa.Integer(), nullable=True),
        sa.Column("gross_monthly_income_eur", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("assets_eur", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_household_members_application_id", "household_members", ["application_id"])

    op.create_table(
        "housing_need",
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("situation", _enum(*NEED_SITUATIONS, name="need_situation"), nullable=False),
        sa.Column("urgency_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("application_id"),
    )

    op.create_table(
        "application_units",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("unit_id", sa.BigInteger(), nullable=False),
        sa.Column("preference_rank", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("application_id", "unit_id", name="uq_application_units"),
    )
    op.create_index("ix_application_units_application_id", "application_units", ["application_id"])
    op.create_index("ix_application_units_unit_id", "application_units", ["unit_id"])

    op.create_table(
        "decisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("application_unit_id", sa.BigInteger(), nullable=False),
        sa.Column("outcome", _enum(*OUTCOMES, name="outcome"), nullable=False),
        sa.Column("rule_id", sa.String(length=40), nullable=False),
        sa.Column("message_fi", sa.Text(), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_unit_id"], ["application_units.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("length(rule_id) > 0", name="ck_decisions_rule_id"),
        sa.CheckConstraint("length(message_fi) > 0", name="ck_decisions_message"),
        sa.CheckConstraint("evidence_json <> '{}'::jsonb", name="ck_decisions_evidence"),
    )
    op.create_index("ix_decisions_application_unit_id", "decisions", ["application_unit_id"])

    op.create_table(
        "viewings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("unit_id", sa.BigInteger(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("capacity > 0", name="ck_viewings_capacity_positive"),
    )
    op.create_index("ix_viewings_unit_id", "viewings", ["unit_id"])

    op.create_table(
        "viewing_bookings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("viewing_id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["viewing_id"], ["viewings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["application_id"], ["applications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("viewing_id", "application_id", name="uq_viewing_bookings"),
    )
    op.create_index("ix_viewing_bookings_viewing_id", "viewing_bookings", ["viewing_id"])
    op.create_index("ix_viewing_bookings_application_id", "viewing_bookings", ["application_id"])

    op.create_table(
        "offers",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("unit_id", sa.BigInteger(), nullable=False),
        sa.Column("contact_name", sa.String(length=160), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("amount_eur", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("amount_eur > 0", name="ck_offers_amount_positive"),
    )
    op.create_index("ix_offers_unit_id", "offers", ["unit_id"])

    op.execute(CAPACITY_GUARD_FUNCTION)
    op.execute(CAPACITY_GUARD_TRIGGER)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_viewing_booking_capacity ON viewing_bookings")
    op.execute("DROP FUNCTION IF EXISTS viewing_booking_capacity_guard()")
    op.drop_table("offers")
    op.drop_table("viewing_bookings")
    op.drop_table("viewings")
    op.drop_table("decisions")
    op.drop_table("application_units")
    op.drop_table("housing_need")
    op.drop_table("household_members")
    op.drop_table("applications")
    op.drop_table("units")
    op.drop_table("properties")
